android.useAndroidX=true
android.enableJetifier=false

org.gradle.jvmargs=-Xmx512M
org.gradle.daemon=true
org.gradle.daemon.maxHeapSize=512M
org.gradle.java.home=/usr/local/google/home/yaoyx/jdk/jdk17/openlogic-openjdk-17.0.14+7-linux-x64
kotlin.daemon.jvmargs=-Xmx1024m --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
